version: "3.8"

services:

    portal_db:
        image: mariadb:10.10-rc
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: portalcapao
            MYSQL_USER: admin
            MYSQL_PASSWORD: secret
        healthcheck:
            test: "/usr/bin/mysql --user=${USER} --password=${USER_PASSWORD} --execute \"SHOW DATABASES;\""
            interval: 3s
            timeout: 1s
            retries: 5

# python service
    # api:
    #     build: ./api
    #     command: python main.py
    #     volumes:
    #         - ./api:/code
    #     ports:
    #         - "9000:9000"
    #     depends_on:
    #         db:
    #             condition: service_healthy