version: "3.8"

services:

    portal_db:
        image: mariadb:10.10-rc
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        healthcheck:
            test: "/usr/bin/mysql --user=${DB_USER} --password=${DB_PASSWORD} --execute \"SHOW DATABASES;\""
            interval: 3s
            timeout: 1s
            retries: 5

    portal_api:
        build: ./api
        command: python main.py
        volumes:
            - ./api:/code
        ports:
            - "9000:9000"
        depends_on:
            portal_db:
                condition: service_healthy


    portal_frontend:
        build: ./frontend
        command: npm start
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/code
        depends_on:
            - portal_api